---
  - name: Install Packets
    yum: name={{item}}
    with_items:
      - python-ceilometer
      - openstack-ceilometer-collector
      - openstack-ceilometer-notification
      - openstack-ceilometer-alarm
      - openstack-ceilometer-common
      - openstack-ceilometer-compute
      - openstack-ceilometer-central
      - openstack-ceilometer-api

  - name: Sync config files
    template: src={{item[0]}}.j2 dest=/etc/{{item[1]}}/{{item[0]}} backup=yes owner=ceilometer group=ceilometer mode=0640
    with_together:
      - [ 'ceilometer.conf']
      - [ 'ceilometer' ]
    notify:
      - enable ceilometer
