---
  - name: start neutron
    shell: systemctl restart {{item}}
    with_items:
      - neutron-server 
      - neutron-linuxbridge-agent 
      - neutron-dhcp-agent 
      - neutron-l3-agent 
    when: ansible_distribution_major_version|int == 7

  - name: enable neutron
    shell: systemctl enable {{item}}
    with_items:
      - neutron-server 
      - neutron-linuxbridge-agent 
      - neutron-dhcp-agent 
      - neutron-l3-agent 
    when: ansible_distribution_major_version|int == 7
