---
  - name: Install Packets
    yum: name={{item}}
    with_items:
      - openstack-neutron
      - openstack-neutron-openvswitch
      - openstack-neutron-linuxbridge
      - python-neutron
      - openstack-neutron-ml2

  - name: Get tenant id
    script: get_tenant_id.py {{CONFIG_KEYSTONE_ADMIN_TOKEN}} http://{{os_keystone}}:35357/v2.0 services
    register: nova_tenant_id

  - name: Sync config files
    template: src={{item}}.j2 dest=/etc/neutron/{{item}} backup=yes owner=neutron group=neutron mode=0640
    with_items:
      - [ 'neutron.conf']
      - [ 'api-paste.ini' ]
      - [ 'dhcp_agent.ini' ]
      - [ 'l3_agent.ini' ]
      - [ 'plugins/ml2/ml2_conf.ini' ]
      - [ 'plugins/linuxbridge/linuxbridge_conf.ini' ]
    notify:
      - enable neutron

  - name: change configs
    shell: rm -f /etc/neutron/plugin.ini

  - name: change configs
    shell: ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini

  - name: create neutron
    script: python neutron.py
