---
  - name: start keystone
    shell: systemctl restart {{item}}
    with_items:
        - openstack-keystone
    when: ansible_distribution_major_version|int == 7

  - name: enable keystone
    shell: systemctl enable {{item}}
    with_items:
        - openstack-keystone
    when: ansible_distribution_major_version|int == 7
