---
- name: Install Packets
  yum: name={{item}}
  with_items:
    - python-cinder
    - openstack-cinder

- name: Sync config files
  template: src={{item}}.j2 dest=/etc/cinder/{{item}} backup=yes owner=cinder group=cinder mode=0640
  with_items:
    - [ 'cinder.conf']
    - [ 'api-paste.ini' ]
  notify:
    - enable cinder

- name: generate ceph client keys
  shell: ceph auth get-or-create client.{{item}} >/etc/ceph/ceph.client.{{item}}.keyring
  ignore_errors: True
  with_items:
    - cinder

- name: change ceph client key credentials
  shell: chown glance. /etc/ceph/ceph.client.{{item}}.keyring
  ignore_errors: True
  with_items:
    - cinder


