
  - name: start ceilometer
    shell: systemctl restart {{item}}
    with_items:
      - openstack-ceilometer-api 
      - openstack-ceilometer-central 
      - openstack-ceilometer-collector 
      - openstack-ceilometer-alarm-notifier 
      - openstack-ceilometer-alarm-evaluator 
    when: ansible_distribution_major_version|int == 7

  - name: enable ceilometer
    shell: systemctl enable {{item}}
    with_items:
      - openstack-ceilometer-api 
      - openstack-ceilometer-central 
      - openstack-ceilometer-collector 
      - openstack-ceilometer-alarm-notifier 
      - openstack-ceilometer-alarm-evaluator 
    when: ansible_distribution_major_version|int == 7

  - name: start cinder
    shell: systemctl restart {{item}}
    with_items:
      - openstack-cinder-api
      - openstack-cinder-scheduler
      - openstack-cinder-volume 
    when: ansible_distribution_major_version|int == 7

  - name: enable cinder
    shell: systemctl enable {{item}}
    with_items:
      - openstack-cinder-api
      - openstack-cinder-scheduler
      - openstack-cinder-volume 
    when: ansible_distribution_major_version|int == 7

  - name: start glance
    shell: systemctl restart {{item}}
    with_items:
      - openstack-glance-api
      - openstack-glance-registry
    when: ansible_distribution_major_version|int == 7

  - name: enable glance
    shell: systemctl enable {{item}}
    with_items:
      - openstack-glance-api
      - openstack-glance-registry
    when: ansible_distribution_major_version|int == 7

  - name: start neutron
    shell: systemctl restart {{item}}
    with_items:
      - neutron-server 
      - neutron-linuxbridge-agent 
      - neutron-dhcp-agent 
      - neutron-l3-agent 
    when: ansible_distribution_major_version|int == 7

  - name: enable neutron
    shell: systemctl enable {{item}}
    with_items:
      - neutron-server 
      - neutron-linuxbridge-agent 
      - neutron-dhcp-agent 
      - neutron-l3-agent 
    when: ansible_distribution_major_version|int == 7

  - name: start nova
    shell: systemctl restart {{item}}
    with_items:
      - openstack-nova-conductor
      - openstack-nova-api
      - openstack-nova-scheduler
      - openstack-nova-novncproxy
      - openstack-nova-consoleauth
      - openstack-nova-cert
    when: ansible_distribution_major_version|int == 7

  - name: enable nova
    shell: systemctl enable {{item}}
    with_items:
      - openstack-nova-conductor
      - openstack-nova-api
      - openstack-nova-scheduler
      - openstack-nova-novncproxy
      - openstack-nova-consoleauth
      - openstack-nova-cert
    when: ansible_distribution_major_version|int == 7
