INSERT INTO `gc_payment_product` VALUES (1, 'Visa', 1, 1);
INSERT INTO `gc_payment_product` VALUES (2, 'AMEX/American Express', 1, 2);
INSERT INTO `gc_payment_product` VALUES (3, 'MasterCard', 1, 3);
INSERT INTO `gc_payment_product` VALUES (111, 'Visa Delta', 1, 15);
INSERT INTO `gc_payment_product` VALUES (114, 'Visa Debit', 1, 12);
INSERT INTO `gc_payment_product` VALUES (119, 'MasterCard Debit', 1, 13);
INSERT INTO `gc_payment_product` VALUES (122, 'Visa Electron', 1, 10);
INSERT INTO `gc_payment_product` VALUES (123, 'Dankort', 1, 6);
INSERT INTO `gc_payment_product` VALUES (125, 'JCB', 1, 9);
INSERT INTO `gc_payment_product` VALUES (809, 'iDEAL', 1, 11);
INSERT INTO `gc_payment_product` VALUES (836, 'Sofort', 1, 7);
INSERT INTO `gc_payment_product` VALUES (841, 'WebMoney', 1, 18);
INSERT INTO `gc_payment_product` VALUES (1503, 'Boleto Bancário', 1, 14);
