---
  - name: start cinder
    shell: systemctl restart {{item}}
    with_items:
      - openstack-cinder-api
      - openstack-cinder-scheduler
      - openstack-cinder-volume 
    when: ansible_distribution_major_version|int == 7

  - name: enable cinder
    shell: systemctl enable {{item}}
    with_items:
      - openstack-cinder-api
      - openstack-cinder-scheduler
      - openstack-cinder-volume 
    when: ansible_distribution_major_version|int == 7
