#!/bin/bash

running=$(ps aux|grep 9a700bbafa79055f48c80c20a55f03f9|grep 'sh -c '|grep -v 'grep'|wc -l)
if [ "$running" -gt 1 ]; then
        echo "$(ps aux|grep 9a700bbafa79055f48c80c20a55f03f9|grep 'sh -c '|grep -v 'grep')"
        echo "already running $0 ($running) $(date +'%Y-%m-%d %T')"
        exit 1
fi

hz_wikipass_host=115.236.98.67
hz_wikipass_port=873
extra_passwd=/etc/corpapp/.ht.corpapp.ext.passwd
rsync_pwd=/etc/rsync.pwd

env_conf=$(dirname $0)/environments.sh
if [ -f "$env_conf" ]; then
    source $env_conf
fi

/usr/bin/rsync -vzrtopg --port=$hz_wikipass_port --progress product@$hz_wikipass_host::corp/.ht.lebbay.passwd /etc/corpapp/.ht.corpapp.passwd --password-file=$rsync_pwd

if [ -f "$extra_passwd" ]; then
    cat $extra_passwd >> /etc/corpapp/.ht.corpapp.passwd
fi

