#!/bin/bash
source $(dirname $0)/config_moni.conf
now=$(date +%Y%m%d%T)

if [[ -z $name ]]
then
    name=${0#*rsync}
fi

cd /tmp
if [ -f "over$name" ]
then
        echo $now $name
        check_md5=$(cat /tmp/over$name)
        rm -rf /tmp/over$name
#        . /var/job/rsyncjjshouse.inc

        rm -rf /tmp/$name.tar.gz /tmp/$name

        /usr/bin/rsync -vzrtopg -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress --delete syncer@$local_server:/opt/data1/code/$name.tar.gz /tmp
        cd /tmp
        file_md5=$(md5sum $name.tar.gz|awk '{print $1}')
        echo "file_md5:$file_md5 check_md5:$check_md5"
        if [[ $check_md5 != $file_md5 ]]
        then
                echo "file md5 error"
                rm -rf /tmp/$name.tar.gz /tmp/$name
                exit
        fi

        tar xzf $name.tar.gz

        if [[ $? -ne 0 ]]
        then
                echo "file rsync error"
                exit
        fi

        /usr/bin/rsync -vzrtopg --progress --delete --exclude "/application/osticket" --exclude "/application/languages" --exclude "/application/ru" --exclude "/application/fi" --exclude "/application/nl" --exclude "/application/da" --exclude "/application/pt" --exclude "/application/it" --exclude "/sitemap/files" --exclude "/application/no" --exclude "/application/se" --exclude "/application/es" --exclude "/application/fr" --exclude "/application/de" --exclude "data" --exclude "userfiles"  --exclude "templates" /tmp/$name/ /var/www/http/$name
        echo

        rm -rf /tmp/$name.tar.gz /tmp/$name

        . /var/job/rsynclestore.inc

	dir=/opt/data1/tmp
	mkdir -p $dir
	for i in `find /var/www/http/lestore/application/templates/ztec/ -type f `
	do
        	mv $i $dir/
	done
	rm -rf $dir/*
	mv /opt/data1/nginxproxycache/proxy_cache_dir/* $dir/
	rm -rf $dir/* &

fi
